### ISSUE TITLE
I do not understand the usage of this parameter in oxford.yaml...

### ISSUE THREAD

**Issue by hitsz-zuoqi** [PyRetri/PyRetri#30]
train_fea_dir: "/data/features/best_features/paris"  # path of the features for training SVD.

I find this in oxford.yaml, and it is strange that when I run main/index.py, the shell post a error:
`[LoadFeature]: loading feature from /mnt/ceph/home/richardzuo/wx_yszm/ft_local/PyRetri-master/features/oxford/query/part_0.json...
[LoadFeature] Success, total 55 images, 
 feature names: dict_keys(['pool5_GAP'])
[LoadFeature]: loading feature from /mnt/ceph/home/richardzuo/wx_yszm/ft_local/PyRetri-master/features/oxford/gallery/part_1.json...
[LoadFeature]: loading feature from /mnt/ceph/home/richardzuo/wx_yszm/ft_local/PyRetri-master/features/oxford/gallery/part_0.json...
[LoadFeature] Success, total 5063 images, 
 feature names: dict_keys(['pool5_GAP'])
Traceback (most recent call last):
  File "main/index.py", line 48, in <module>
    main()
  File "main/index.py", line 36, in main
    index_helper = build_index_helper(cfg.index)
  File "/data1/anaconda3/envs/PyRetri/lib/python3.7/site-packages/pyretri-0.1.0+unknown-py3.7.egg/pyretri/index/builder.py", line 89, in build_index_helper
    dim_processors = build_processors(cfg["feature_names"], cfg.dim_processors)
  File "/data1/anaconda3/envs/PyRetri/lib/python3.7/site-packages/pyretri-0.1.0+unknown-py3.7.egg/pyretri/index/builder.py", line 60, in build_processors
    processors.append(simple_build(name, cfg, DIMPROCESSORS, feature_names=feature_names))
  File "/data1/anaconda3/envs/PyRetri/lib/python3.7/site-packages/pyretri-0.1.0+unknown-py3.7.egg/pyretri/utils/builder.py", line 50, in simple_build
    return module(hps=hps, **kwargs)
  File "/data1/anaconda3/envs/PyRetri/lib/python3.7/site-packages/pyretri-0.1.0+unknown-py3.7.egg/pyretri/index/dim_processor/dim_processors_impl/svd.py", line 42, in __init__
    self._train(self._hyper_params["train_fea_dir"])
  File "/data1/anaconda3/envs/PyRetri/lib/python3.7/site-packages/pyretri-0.1.0+unknown-py3.7.egg/pyretri/index/dim_processor/dim_processors_impl/svd.py", line 51, in _train
    train_fea, _, _ = feature_loader.load(fea_dir, self.feature_names)
  File "/data1/anaconda3/envs/PyRetri/lib/python3.7/site-packages/pyretri-0.1.0+unknown-py3.7.egg/pyretri/index/utils/feature_loader.py", line 67, in load
    assert os.path.exists(fea_dir), "non-exist feature path: {}".format(fea_dir)`

can you explain it ? thanks~

**Comment by hitsz-zuoqi** [comment]
Besides, I do not find  any dataset named paris in README~

**Comment by JH95-ai** [comment]
> Besides, I do not find any dataset named paris in README~

Look issue three,it will help you
