### ISSUE TITLE
unable to loop over dataloder.

### ISSUE THREAD

**Issue by aiwithshekhar** [PyRetri/PyRetri#34]
when i run `python main/extract_feature.py -dj data_jsons/oxford_gallery.json -sp data/features/oxford/gallery.pickle -cfg configs/oxford.yaml` i get below output. This do not dump any pickle file, after little debugging i found out it does not go inside [https://github.com/PyRetri/PyRetri/blob/master/pyretri/extract/helper/helper.py/#L109](url) dataloader loop.

0it [00:00, ?it/s]
time:  0.47732090950012207

**Comment by A-hardworking-people** [comment]
can I know how do you fix the above mention problem, thank you very much！

**Comment by aiwithshekhar** [comment]
the dataloader was empty that's why it was unable to loop over. It has to do with the pickle file generation so should check that.

**Comment by A-hardworking-people** [comment]
Do you mean there is an error in the step of making Data Json? Is there a problem with the generated Json file?
How did you solve it?
Thank you so much for your reply. May I add your QQ to ask you for advice? Thank you very much!

**Comment by A-hardworking-people** [comment]
**now the problem has been:**
$python3 main/extract_feature.py -dj data_jsons/oxford_query.json -sp data/features/oxford/query/ -cfg configs/oxford.yaml

[LoadStateDict]: shape mismatch in parameter classifier.6.bias, torch.Size([1000]) vs torch.Size([1365])
[LoadStateDict]: shape mismatch in parameter classifier.6.weight, torch.Size([1000, 4096]) vs torch.Size([1365, 4096])
[LoadStateDict]: missing keys or mismatch param in state_dict: {'classifier.6.bias', 'classifier.6.weight'}
  0%|                                                                                                                                                                                | 0/4 [00:00<?, ?it/s][DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/query/balliol_000194.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/query/oxford_002985.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/query/christ_church_000179.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/query/pitt_rivers_000153.jpg'
Traceback (most recent call last):
  File "main/extract_feature.py", line 52, in <module>
    main()
  File "main/extract_feature.py", line 48, in main
    extract_helper.do_extract(dataloader, args.save_path, args.save_interval)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/extract/helper/helper.py", line 109, in do_extract
    for _, batch in zip(pbar, dataloader):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/datasets/folder/folder_impl/folder.py", line 78, in __getitem__
    img = self.transformer(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/datasets/transformer/transformers_impl/transformers.py", line 107, in __call__
    return self.t_transformer(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 198, in __call__
    return F.resize(img, self.size, self.interpolation)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 238, in resize
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'NoneType'>

  0%|

**Comment by A-hardworking-people** [comment]
**Now the problem has been:**

$python3 main/extract_feature.py -dj data_jsons/oxford_gallery.json -sp data/features/oxford/gallery/ -cfg configs/oxford.yaml

[LoadStateDict]: shape mismatch in parameter classifier.6.bias, torch.Size([1000]) vs torch.Size([1365])
[LoadStateDict]: shape mismatch in parameter classifier.6.weight, torch.Size([1000, 4096]) vs torch.Size([1365, 4096])
[LoadStateDict]: missing keys or mismatch param in state_dict: {'classifier.6.bias', 'classifier.6.weight'}
  0%|                                                                                                                                                                              | 0/317 [00:00<?, ?it/s][DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/cornmarket_000018.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_002551.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_000487.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_003095.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/new_001080.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/magdalen_001153.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_003672.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/oxford_000196.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/ashmolean_000287.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000048.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/magdalen_000712.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000602.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/jesus_000134.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/worcester_000070.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000329.jpg'
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/magdalen_000228.jpg'
Traceback (most recent call last):
  File "main/extract_feature.py", line 52, in <module>
[DataSet]: WARNING image can not be loaded: [Errno 2] No such file or directory: 'data/cbir/oxford/gallery/christ_church_000349.jpg'
    main()
  File "main/extract_feature.py", line 48, in main
    extract_helper.do_extract(dataloader, args.save_path, args.save_interval)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/extract/helper/helper.py", line 109, in do_extract
    for _, batch in zip(pbar, dataloader):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/datasets/folder/folder_impl/folder.py", line 78, in __getitem__
    img = self.transformer(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/pyretri-0.1.0+unknown-py3.6.egg/pyretri/datasets/transformer/transformers_impl/transformers.py", line 107, in __call__
    return self.t_transformer(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 198, in __call__
    return F.resize(img, self.size, self.interpolation)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 238, in resize
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'NoneType'>

  0%|                                                                                                                                                                              | 0/317 [00:00<?, ?it/s]
