### ISSUE TITLE
AssertionError at statement 'assert name in registry' in utils\builder.py

### ISSUE THREAD

**Issue by Junah-Park** [PyRetri/PyRetri#41]
While attempting extraction through Windows Anaconda console:

python C:\Users\user\Documents\Projects\PyRetri\main\extract_feature.py -dj C:\Users\user\Documents\Projects\PyRetri\data_jsons\gallery.json -sp C:\Users\user\Documents\Projects\PyRetri\data\features -cfg configs/nft.yaml

Traceback (most recent call last):
  File "C:\Users\user\Documents\Projects\PyRetri\main\extract_feature.py", line 52, in <module>
    main()
  File "C:\Users\user\Documents\Projects\PyRetri\main\extract_feature.py", line 40, in main
    dataset = build_folder(args.data_json, cfg.datasets)
  File "C:\Users\user\Anaconda3\lib\site-packages\pyretri-0.1.0+unknown-py3.8.egg\pyretri\datasets\builder.py", line 61, in build_folder
    trans = build_transformers(cfg.transformers)
  File "C:\Users\user\Anaconda3\lib\site-packages\pyretri-0.1.0+unknown-py3.8.egg\pyretri\datasets\builder.py", line 45, in build_transformers
    transformers.append(simple_build(name, cfg, TRANSFORMERS))
  File "C:\Users\user\Anaconda3\lib\site-packages\pyretri-0.1.0+unknown-py3.8.egg\pyretri\utils\builder.py", line 42, in simple_build
    assert name in registry
AssertionError

**Comment by Junah-Park** [comment]
nft.yaml configured incorrectly
